version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
       - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: sudo chmod +x ./gradlew
	  - run: echo "yamas"


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
