version: 2
jobs:
  build:
    working_directory: /app
    docker:
       - image: circleci/node:4.8.2
    steps:
      - checkout
       - run:
      name: chmod permissions
      command: sudo chmod +x ./gradlew
      - restore_cache:
          key: gradle-deps-{{ checksum "build.gradle" }}
      - run:
          name: Test application
          command: ./gradlew build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
